### ISSUE TITLE
Please create more recent tagged release, 2.9.0 is outdated

### ISSUE THREAD

**Issue by nikosmeds** [fubarhouse/ansible-role-golang#149]
Heyo :) thanks for maintaining this role.

Can you guys please tag a new release with the recent changes? We pin our Ansible role versions, and `2.9.0` doesn't have any updates from the previous ~6 months.

Thank you!

**Comment by fubarhouse** [comment]
I'll organise something for you 🙂

**Comment by fubarhouse** [comment]
Release `v2.10.0` is now out, pending release notes.

**Comment by nikosmeds** [comment]
Sweet, thank you

**Comment by fubarhouse** [comment]
Release notes now available, closing 🙂
