### ISSUE TITLE
Permission issue when installing dependencies on Debian

### ISSUE THREAD

**Issue by RobQuistNL** [fubarhouse/ansible-role-golang#156]
Hiya!

Now, it might be because I'm a big noob at ansible, but it looks like this task: https://github.com/fubarhouse/ansible-role-golang/blob/master/tasks/tasks-Debian.yml is failing;

```
fatal: [c1]: FAILED! => {"attempts": 1, "changed": false, "msg": "'/usr/bin/apt-mark manual curl gcc git findutils make rsync tar' failed: E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "rc": 100, "stderr": "E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "stderr_lines": ["E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)", "E: Failed to write temporary StateFile /var/lib/apt/extended_states"], "stdout": "curl was already set to manually installed.\ngcc was already set to manually installed.\ngit was already set to manually installed.\nfindutils was already set to manually installed.\n", "stdout_lines": ["curl was already set to manually installed.", "gcc was already set to manually installed.", "git was already set to manually installed.", "findutils was already set to manually installed."]}
```

Feels like that will be fixed by adding "become: true" into that task (since APT requires root), but maybe I'm just doing something wrong.

**Comment by RobQuistNL** [comment]
I think I fixed it by including my role like so; (in my other rule):

```
- name: Install GoLang
  include_role:
    name: fubarhouse.golang
  args:
    apply:
      become: yes
```

**Comment by fubarhouse** [comment]
@RobQuistNL nice. That would be my recommendation.
Using the system package manager does require privilege escalation - so alternatively you can build it from source and install it to a location you have access to.

Welcome to Ansible, by the way :)

**Comment by RobQuistNL** [comment]
Thanks a ton! Thanks for these roles, too :) Lovely to bake an automated system setup using Ansible.

**Comment by phelipetls** [comment]
I also stumbled upon this problem and had to change GOPATH to be `{{ ansible_env.HOME }}/go`, otherwise it'd be `/root/go`, which was not what I expected but I'm very unfamiliar with Go and Ansible so I'm not sure if it's the right thing to do.

**Comment by fubarhouse** [comment]
> I also stumbled upon this problem and had to change GOPATH to be `{{ ansible_env.HOME }}/go`, otherwise it'd be `/root/go`, which was not what I expected but I'm very unfamiliar with Go and Ansible so I'm not sure if it's the right thing to do.

I love the approach. I must admit my time is more precious these days...
Let me know if you're not happy or comfortable to put this together yourself - and I'll organise it.

Happy either way, but the best way to learn is to get your hands dirty - the opportunity is yours if you want it :)
